# ===============================
# SERVER
# ===============================
server.port=8083

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/carwash_order_db
spring.datasource.username=root
spring.datasource.password=#Sarthak@76342

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional but safe
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# EUREKA (OPTIONAL HERE)
# ===============================
eureka.instance.prefer-ip-address=true
